### ISSUE TITLE
Return Light

### ISSUE THREAD

**Issue by Haden2** [Haden2/Spectrum#19]
Return the light when the enemy is caught after running away. Then return enemy to normal stalk mode. This is basically creating a version of tag.

**Comment by thomas-j-sell** [comment]
This should relatively simple to implement.  Put a boolean "hasPossesionOfGlasses" or similar in the enemyDamage and add logic in the collision detector to enable and disable the flashlight based on the boolean.

We just need a way to toggle between running away mode and stalking mode, and add a check to prevent the flashlight from being continuously toggled while the player and enemy are colliding.

**Comment by Haden2** [comment]
Yeah the boolean wont be hard to do. I looked into the navigating away from player a little bit before work. What I think I will do is when we set up a room, tag the room as something, like room1. Then when toggleglasses is off, I can switch the enemies navigation from player to room. This wont be hard to do. *knocks on wood.

**Comment by thomas-j-sell** [comment]
That sounds pretty solid.

## 

Thomas Sell

**Comment by Haden2** [comment]
What does? The sound of knocking on wood or the plan? :P

**Comment by thomas-j-sell** [comment]
Yes.  

## 

Thomas Sell

**Comment by Haden2** [comment]
Hahaha. Oh also, when I get home I'm going to change the design of the mannequin. I was thinking to myself now that I know the setting, why would there be a mannequin in a science/health facility? So I'm going to change his design to look more like a plastic model that you would see in medical teaching areas. I'll find some pictures and update that. He will still have the same ability. But his starting location and overall presence there will make more sense to the story. The clown is just there. Maybe there was a circus nearby or a clown was buried under the building, or he was there to make the children happy. I also have an idea for another monster and spectrum design. I wont add that to the list until I get a better understanding on how I want to implement it.

**Comment by Haden2** [comment]
![male-torso-model](https://cloud.githubusercontent.com/assets/10826350/6163584/60459e98-b262-11e4-80ac-c7238eec8ad8.jpg)

**Comment by Haden2** [comment]
I made a commit in another branch but it still has some kinks to it. I'll see if I can fix those tonight and then pull it.

**Comment by Haden2** [comment]
Nope. Need to figure out how to add a delay to returning light or figure out path complete status code to only return light when the enemy has reached its destination. As of now it is just giving my light back as soon as the enemy takes it. I commented out the code that I worked on. Stupid weekend shift has me working at 3 so I cannot work on it further until I get back.
