### ISSUE TITLE
Unity Update

### ISSUE THREAD

**Issue by Haden2** [Haden2/Spectrum#23]
Unity updated to a new version. Should we download it? I don't know how that works. Like is our stuff just carried over?

**Comment by thomas-j-sell** [comment]
I'll take a look at see what kinda changes there all.  It will likely be fine, we'll just want to get all our stuff merged into master before we upgrade.

## 

Thomas Sell

**Comment by Haden2** [comment]
From what I was getting out of it there were UI updates and everything can have shadows

**Comment by thomas-j-sell** [comment]
What version do you have?  Check for updates tells me I have the latest version?  I don't see anything gamebreakinig in the latest release notes, so we should be good.

**Comment by Haden2** [comment]
4.6.2 Is the current version and I have 4.6.1

**Comment by thomas-j-sell** [comment]
I’m already on 4.6.2, so we should be good.  

## 

Thomas Sell
