### ISSUE TITLE
Pick up item text

### ISSUE THREAD

**Issue by Haden2** [Haden2/Spectrum#5]
Activates when walking into sphere. Stays activated however.

**Comment by Haden2** [comment]
I can fix this by creating another variable 'blank' and setting that to equal 0 color. I have done this so now the code with say if I am not touching the pickup tag, return the message to blank. I can surround the sphere with objects that dont have the pickup tag so it goes away.

**Comment by Haden2** [comment]
Created four planes around the sphere so the text goes away when backing away from the object. Not the most effective way in the world because I know there is code to do this, but it works. Sooo...

**Comment by thomas-j-sell** [comment]
It seems very wasteful to create 4 extra objects to deactivate the text.  At this point in the project I suggest we find a simpler solution since this will likely come up a lot more.  It's easier to get it right now then re-do it a bunch of times later.

**Comment by Haden2** [comment]
Yeah, you are right. I actually just need to look back at the tutorials, but I was just trying to fix the issue as soon as possible because it was taking me a long time to get around to it.

**Comment by thomas-j-sell** [comment]
That's fair.  The balance between doing it right and doing it fast is always hard to get right.

## 

Thomas Sell

**Comment by Haden2** [comment]
DONE! The four planes are gone and the code works. Moving on to the next thing now.
